name: filternet
channels:
  - pytorch
  - defaults

dependencies:
  - anaconda == 2019.10  # unpin this for latest packages; this pins lots of versions.
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - pytorch == 1.0.1 # unpin for latest pytorch
  - scikit-learn
  - scipy
  - seaborn
  - traits
  - pip:
      - hyperopt
      - pyEDFlib
      - ray == 0.8.4 # you could unpin, but api seems unstable
      - tabulate
      - torchsummary
      - torchsummaryX
      - typing
      - ward-metrics == 0.9.5 # probably doesn't need to be pinned



